services:
  - type: static
    name: suivi-deploiement-mobiliers
    env: static
    buildCommand: npm install && npm run build
    publish: dist/browser
    staticPublishOptions:
      redirects:
        - source: "/*"
          destination: "/index.html"
          statusCode: 200
