export const REGIONS = [
  "PORO", "TCHOLOGO", "BAFING", "WORODOUGOU", "GONTOUGO", "NAWA",
  "LOH-DJIBOUA", "MORONOU", "N'ZI", "CAVALLY", "GUEMON", "TONKPI",
  "INDENIE-DJUABLIN", "SUD-COMOE", "AGNEBY-IASSA", "ME"
];

export const TYPES_MOBILIER = [
  "ARMOIRE DE RANGEMENT",
  "BUREAU AVEC RETOUR",
  "CHAISE VISITEUR",
  "CHAISE PLASTIQUE",
  "CLASSEUR À DOSSIERS",
  "FAUTEUIL AGENT",
  "TABLE DE REUNION",
  "MOTO"
];

export const TYPES_PERSONNEL = [
  "RR-AFOR",
  "RD-AFOR",
  "CESF",
  "CARTOGRAPHE",
  "INFORMATICIEN"
];

export const COLORS =
  ['#0088FE',
  '#00C49F',
    '#FFBB28',
    '#FF8042',
    '#8884d8',
    '#83a6ed'];
